// Sample college data
const colleges = [
    {
        id: 1,
        name: "NIT Kurukshetra",
        city: "Kurukshetra",
        type: "Government",
        category: "engineering",
        courses: ["btech", "mba"],
        fees: 85000,
        placement: "95%",
        avgPackage: "12 LPA",
        highestPackage: "45 LPA",
        seats: 1200,
        criteria: "JEE Main rank under 25000",
        description: "Premier engineering institute in Haryana",
        facilities: ["Library", "Hostel", "Sports Complex", "Labs"],
        branches: ["CSE", "ECE", "ME", "CE", "EE"]
    },
    {
        id: 2,
        name: "YMCA University",
        city: "Faridabad",
        type: "Government",
        category: "engineering",
        courses: ["btech", "polytechnic"],
        fees: 65000,
        placement: "85%",
        avgPackage: "6 LPA",
        highestPackage: "25 LPA",
        seats: 800,
        criteria: "JEE Main rank under 50000",
        description: "Established engineering university",
        facilities: ["Library", "Hostel", "Cafeteria", "Labs"],
        branches: ["CSE", "IT", "ECE", "ME"]
    },
    {
        id: 3,
        name: "Amity University Gurgaon",
        city: "Gurgaon",
        type: "Private",
        category: "engineering",
        courses: ["btech", "mba", "arts"],
        fees: 180000,
        placement: "80%",
        avgPackage: "5 LPA",
        highestPackage: "18 LPA",
        seats: 2000,
        criteria: "60% in 12th",
        description: "Multi-disciplinary private university",
        facilities: ["Library", "Hostel", "Sports", "Labs", "Auditorium"],
        branches: ["CSE", "IT", "ECE", "ME", "MBA", "BA", "BCom"]
    },
    {
        id: 4,
        name: "Manav Rachna University",
        city: "Faridabad",
        type: "Private",
        category: "engineering",
        courses: ["btech", "mba", "arts"],
        fees: 150000,
        placement: "75%",
        avgPackage: "4.5 LPA",
        highestPackage: "15 LPA",
        seats: 1500,
        criteria: "55% in 12th",
        description: "Well-known private university",
        facilities: ["Library", "Hostel", "Sports", "Labs"],
        branches: ["CSE", "ECE", "ME", "MBA", "BBA"]
    },
    {
        id: 5,
        name: "Government Polytechnic Karnal",
        city: "Karnal",
        type: "Government",
        category: "polytechnic",
        courses: ["polytechnic"],
        fees: 25000,
        placement: "70%",
        avgPackage: "3 LPA",
        highestPackage: "8 LPA",
        seats: 600,
        criteria: "50% in 10th",
        description: "Government polytechnic college",
        facilities: ["Library", "Hostel", "Workshop", "Labs"],
        branches: ["Civil", "Mechanical", "Electrical", "Computer"]
    },
    {
        id: 6,
        name: "Kurukshetra University",
        city: "Kurukshetra",
        type: "Government",
        category: "arts",
        courses: ["arts"],
        fees: 15000,
        placement: "60%",
        avgPackage: "3.5 LPA",
        highestPackage: "10 LPA",
        seats: 3000,
        criteria: "50% in 12th",
        description: "State university offering various programs",
        facilities: ["Library", "Hostel", "Sports", "Auditorium"],
        branches: ["BA", "BSc", "BCom", "MA", "MSc"]
    },
    {
        id: 7,
        name: "MDU Rohtak",
        city: "Rohtak",
        type: "Government",
        category: "arts",
        courses: ["arts", "mba"],
        fees: 18000,
        placement: "65%",
        avgPackage: "4 LPA",
        highestPackage: "12 LPA",
        seats: 2500,
        criteria: "50% in 12th",
        description: "Maharshi Dayanand University",
        facilities: ["Library", "Hostel", "Sports", "Labs"],
        branches: ["BA", "BSc", "BCom", "MBA", "MA"]
    },
    {
        id: 8,
        name: "The NorthCap University",
        city: "Gurgaon",
        type: "Private",
        category: "engineering",
        courses: ["btech", "mba"],
        fees: 165000,
        placement: "82%",
        avgPackage: "6.5 LPA",
        highestPackage: "22 LPA",
        seats: 1000,
        criteria: "60% in 12th, JEE Main",
        description: "Private engineering university",
        facilities: ["Library", "Hostel", "Sports", "Labs", "Cafeteria"],
        branches: ["CSE", "IT", "ECE", "ME", "MBA"]
    }
];
