# All Haryana Colleges seed data

HARYANA_COLLEGES = [

    # ── Engineering / B.Tech ─────────────────────────────────────────────────
    {
        "name": "NIT Kurukshetra",
        "city": "Kurukshetra", "type": "Government", "category": "engineering",
        "fees": 85000, "placement": "95%", "avg_package": "12 LPA", "highest_package": "45 LPA",
        "seats": 1240, "criteria": "JEE Main rank under 25000",
        "description": "National Institute of Technology Kurukshetra, premier NIT offering B.Tech, M.Tech and PhD.",
        "courses": ["btech", "mba"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "EE", "IT", "Chemical Engineering"],
        "facilities": ["Central Library", "Boys & Girls Hostel", "Sports Complex", "Advanced Labs", "Cafeteria", "Medical Centre", "Wi-Fi Campus"],
    },
    {
        "name": "J.C. Bose University of Science & Technology YMCA",
        "city": "Faridabad", "type": "Government", "category": "engineering",
        "fees": 67000, "placement": "85%", "avg_package": "6 LPA", "highest_package": "25 LPA",
        "seats": 840, "criteria": "JEE Main rank under 50000",
        "description": "Government engineering university in Faridabad offering B.Tech and M.Tech programs.",
        "courses": ["btech", "polytechnic"],
        "branches": ["CSE", "IT", "ECE", "ME", "Civil Engineering"],
        "facilities": ["Library", "Hostel", "Cafeteria", "Labs", "Sports Ground"],
    },
    {
        "name": "Deenbandhu Chhotu Ram University of Science & Technology",
        "city": "Sonipat", "type": "Government", "category": "engineering",
        "fees": 72000, "placement": "78%", "avg_package": "5.5 LPA", "highest_package": "20 LPA",
        "seats": 900, "criteria": "JEE Main rank under 60000",
        "description": "State government university in Sonipat offering B.Tech, M.Tech and MBA.",
        "courses": ["btech", "mba"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "EE", "IT"],
        "facilities": ["Library", "Hostel", "Sports Ground", "Labs", "Cafeteria"],
    },
    {
        "name": "Guru Jambheshwar University of Science & Technology",
        "city": "Hisar", "type": "Government", "category": "engineering",
        "fees": 68000, "placement": "72%", "avg_package": "5 LPA", "highest_package": "18 LPA",
        "seats": 800, "criteria": "JEE Main rank under 70000",
        "description": "State university in Hisar offering engineering, pharmacy and management programs.",
        "courses": ["btech", "mba"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "EE", "Pharmacy"],
        "facilities": ["Library", "Hostel", "Sports", "Labs", "Medical Centre"],
    },
    {
        "name": "Indira Gandhi University Meerpur",
        "city": "Rewari", "type": "Government", "category": "engineering",
        "fees": 55000, "placement": "65%", "avg_package": "4 LPA", "highest_package": "12 LPA",
        "seats": 600, "criteria": "JEE Main / 60% in 12th",
        "description": "State university in Rewari offering engineering and arts programs.",
        "courses": ["btech", "arts"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "BA", "BSc"],
        "facilities": ["Library", "Hostel", "Sports Ground", "Labs"],
    },
    {
        "name": "The NorthCap University",
        "city": "Gurgaon", "type": "Private", "category": "engineering",
        "fees": 165000, "placement": "82%", "avg_package": "6.5 LPA", "highest_package": "22 LPA",
        "seats": 1000, "criteria": "60% in 12th + JEE Main / NCU entrance",
        "description": "Private university in Gurgaon offering engineering, management and law programs.",
        "courses": ["btech", "mba"],
        "branches": ["CSE", "IT", "ECE", "ME", "Civil Engineering", "MBA"],
        "facilities": ["Library", "Hostel", "Sports", "Labs", "Cafeteria", "Auditorium"],
    },
    {
        "name": "Amity University Gurugram",
        "city": "Gurgaon", "type": "Private", "category": "engineering",
        "fees": 185000, "placement": "80%", "avg_package": "5 LPA", "highest_package": "18 LPA",
        "seats": 2000, "criteria": "60% in 12th",
        "description": "Multi-disciplinary private university offering engineering, management, law and arts.",
        "courses": ["btech", "mba", "arts"],
        "branches": ["CSE", "IT", "ECE", "ME", "MBA", "BA", "BCom", "BBA"],
        "facilities": ["Library", "Hostel", "Sports Complex", "Labs", "Auditorium", "Medical Centre"],
    },
    {
        "name": "Manav Rachna University",
        "city": "Faridabad", "type": "Private", "category": "engineering",
        "fees": 150000, "placement": "75%", "avg_package": "4.5 LPA", "highest_package": "15 LPA",
        "seats": 1500, "criteria": "55% in 12th",
        "description": "Well-known private university in Faridabad with strong industry connections.",
        "courses": ["btech", "mba", "arts"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "MBA", "BBA"],
        "facilities": ["Library", "Hostel", "Sports", "Labs", "Cafeteria"],
    },
    {
        "name": "Manav Rachna International Institute of Research and Studies",
        "city": "Faridabad", "type": "Private", "category": "engineering",
        "fees": 160000, "placement": "76%", "avg_package": "4.8 LPA", "highest_package": "16 LPA",
        "seats": 1200, "criteria": "55% in 12th",
        "description": "Deemed university offering engineering, management and applied sciences.",
        "courses": ["btech", "mba"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "MBA"],
        "facilities": ["Library", "Hostel", "Sports", "Labs"],
    },
    {
        "name": "Maharishi Markandeshwar University Mullana",
        "city": "Ambala", "type": "Private", "category": "engineering",
        "fees": 120000, "placement": "74%", "avg_package": "4.5 LPA", "highest_package": "14 LPA",
        "seats": 1100, "criteria": "55% in 12th + JEE Main",
        "description": "Deemed university in Ambala offering engineering, medical and management programs.",
        "courses": ["btech", "mba"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "EE", "MBA"],
        "facilities": ["Library", "Hostel", "Hospital", "Sports", "Labs"],
    },
    {
        "name": "GD Goenka University",
        "city": "Gurgaon", "type": "Private", "category": "engineering",
        "fees": 175000, "placement": "78%", "avg_package": "5.2 LPA", "highest_package": "17 LPA",
        "seats": 1000, "criteria": "60% in 12th",
        "description": "Private university in Gurgaon with modern campus and industry tie-ups.",
        "courses": ["btech", "mba", "arts"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "MBA", "BBA", "BA"],
        "facilities": ["Library", "Hostel", "Sports Complex", "Labs", "Auditorium", "Cafeteria"],
    },
    {
        "name": "Ansal University",
        "city": "Gurgaon", "type": "Private", "category": "engineering",
        "fees": 145000, "placement": "70%", "avg_package": "4.2 LPA", "highest_package": "13 LPA",
        "seats": 800, "criteria": "55% in 12th",
        "description": "Private university in Gurgaon offering engineering, architecture and management.",
        "courses": ["btech", "mba"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "Architecture", "MBA"],
        "facilities": ["Library", "Hostel", "Labs", "Sports", "Design Studio"],
    },
    {
        "name": "PDM University",
        "city": "Bahadurgarh", "type": "Private", "category": "engineering",
        "fees": 110000, "placement": "70%", "avg_package": "4 LPA", "highest_package": "12 LPA",
        "seats": 900, "criteria": "55% in 12th",
        "description": "Private university in Bahadurgarh offering engineering and management.",
        "courses": ["btech", "mba"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "MBA"],
        "facilities": ["Library", "Hostel", "Sports", "Labs"],
    },
    {
        "name": "Starex University",
        "city": "Gurgaon", "type": "Private", "category": "engineering",
        "fees": 105000, "placement": "68%", "avg_package": "3.8 LPA", "highest_package": "11 LPA",
        "seats": 700, "criteria": "50% in 12th",
        "description": "Private university in Gurgaon offering engineering and management programs.",
        "courses": ["btech", "mba"],
        "branches": ["CSE", "ECE", "ME", "MBA"],
        "facilities": ["Library", "Hostel", "Labs", "Sports Ground"],
    },
    {
        "name": "Lingaya's Vidyapeeth",
        "city": "Faridabad", "type": "Private", "category": "engineering",
        "fees": 130000, "placement": "72%", "avg_package": "4.3 LPA", "highest_package": "13 LPA",
        "seats": 1000, "criteria": "55% in 12th",
        "description": "Deemed university in Faridabad offering engineering, management and law.",
        "courses": ["btech", "mba"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "MBA", "LLB"],
        "facilities": ["Library", "Hostel", "Sports", "Labs", "Auditorium"],
    },
    {
        "name": "SGT University",
        "city": "Gurgaon", "type": "Private", "category": "engineering",
        "fees": 125000, "placement": "71%", "avg_package": "4.2 LPA", "highest_package": "13 LPA",
        "seats": 950, "criteria": "55% in 12th",
        "description": "Shree Guru Gobind Singh Tricentenary University in Gurgaon.",
        "courses": ["btech", "mba", "arts"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "MBA", "BA", "Pharmacy"],
        "facilities": ["Library", "Hostel", "Hospital", "Sports", "Labs"],
    },
    {
        "name": "K.R. Mangalam University",
        "city": "Gurgaon", "type": "Private", "category": "engineering",
        "fees": 135000, "placement": "73%", "avg_package": "4.5 LPA", "highest_package": "14 LPA",
        "seats": 850, "criteria": "55% in 12th",
        "description": "Private university in Gurgaon offering engineering, management and commerce.",
        "courses": ["btech", "mba", "arts"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "MBA", "BCom", "BBA"],
        "facilities": ["Library", "Hostel", "Sports", "Labs", "Cafeteria"],
    },
    {
        "name": "Geeta University",
        "city": "Panipat", "type": "Private", "category": "engineering",
        "fees": 100000, "placement": "67%", "avg_package": "3.8 LPA", "highest_package": "11 LPA",
        "seats": 750, "criteria": "50% in 12th",
        "description": "Private university in Panipat offering engineering and management.",
        "courses": ["btech", "mba"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "MBA"],
        "facilities": ["Library", "Hostel", "Labs", "Sports Ground"],
    },
    {
        "name": "Haryana Engineering College Jagadhri",
        "city": "Yamuna Nagar", "type": "Government", "category": "engineering",
        "fees": 60000, "placement": "70%", "avg_package": "4.5 LPA", "highest_package": "14 LPA",
        "seats": 720, "criteria": "JEE Main rank under 80000",
        "description": "Government engineering college in Yamuna Nagar.",
        "courses": ["btech"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "EE"],
        "facilities": ["Library", "Hostel", "Labs", "Sports Ground"],
    },
    {
        "name": "Government Engineering College Bhiwani",
        "city": "Bhiwani", "type": "Government", "category": "engineering",
        "fees": 58000, "placement": "68%", "avg_package": "4.2 LPA", "highest_package": "13 LPA",
        "seats": 600, "criteria": "JEE Main rank under 90000",
        "description": "Government engineering college in Bhiwani.",
        "courses": ["btech"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering"],
        "facilities": ["Library", "Hostel", "Labs", "Sports Ground"],
    },

    # ── MBA / Management ─────────────────────────────────────────────────────
    {
        "name": "IMT Gurgaon",
        "city": "Gurgaon", "type": "Private", "category": "engineering",
        "fees": 1600000, "placement": "98%", "avg_package": "14 LPA", "highest_package": "50 LPA",
        "seats": 480, "criteria": "CAT 85+ percentile",
        "description": "Institute of Management Technology Gurgaon, one of the top B-schools in India.",
        "courses": ["mba"],
        "branches": ["MBA - Finance", "MBA - Marketing", "MBA - HR", "MBA - Operations", "MBA - IT"],
        "facilities": ["Library", "Hostel", "Sports Complex", "Auditorium", "Cafeteria", "Wi-Fi Campus"],
    },
    {
        "name": "MDU Rohtak - Institute of Management Studies",
        "city": "Rohtak", "type": "Government", "category": "engineering",
        "fees": 45000, "placement": "72%", "avg_package": "5 LPA", "highest_package": "14 LPA",
        "seats": 120, "criteria": "CAT / MAT / CMAT + 50% in graduation",
        "description": "MBA program under Maharshi Dayanand University, one of the oldest universities in Haryana.",
        "courses": ["mba"],
        "branches": ["MBA - Finance", "MBA - Marketing", "MBA - HR", "MBA - IT"],
        "facilities": ["Library", "Hostel", "Computer Lab", "Seminar Hall"],
    },
    {
        "name": "University Institute of Engineering & Technology MDU",
        "city": "Rohtak", "type": "Government", "category": "engineering",
        "fees": 62000, "placement": "74%", "avg_package": "5.2 LPA", "highest_package": "16 LPA",
        "seats": 480, "criteria": "JEE Main rank under 75000",
        "description": "Engineering institute under MDU Rohtak offering B.Tech programs.",
        "courses": ["btech"],
        "branches": ["CSE", "ECE", "ME", "Civil Engineering", "IT"],
        "facilities": ["Library", "Hostel", "Labs", "Sports Ground", "Cafeteria"],
    },

    # ── Arts / Science / Commerce ────────────────────────────────────────────
    {
        "name": "Kurukshetra University",
        "city": "Kurukshetra", "type": "Government", "category": "arts",
        "fees": 15000, "placement": "60%", "avg_package": "3.5 LPA", "highest_package": "10 LPA",
        "seats": 3000, "criteria": "50% in 12th",
        "description": "One of the oldest and largest universities in Haryana offering arts, science, commerce and law.",
        "courses": ["arts", "mba"],
        "branches": ["BA", "BSc", "BCom", "MA", "MSc", "MCom", "LLB", "BCA"],
        "facilities": ["Central Library", "Hostel", "Sports Complex", "Auditorium", "Medical Centre"],
    },
    {
        "name": "Maharshi Dayanand University",
        "city": "Rohtak", "type": "Government", "category": "arts",
        "fees": 18000, "placement": "65%", "avg_package": "4 LPA", "highest_package": "12 LPA",
        "seats": 2500, "criteria": "50% in 12th",
        "description": "Major state university in Rohtak offering arts, science, commerce, law and management.",
        "courses": ["arts", "mba"],
        "branches": ["BA", "BSc", "BCom", "MA", "MSc", "MBA", "LLB", "BCA", "MCA"],
        "facilities": ["Library", "Hostel", "Sports", "Labs", "Auditorium"],
    },
    {
        "name": "Chaudhary Devi Lal University",
        "city": "Sirsa", "type": "Government", "category": "arts",
        "fees": 14000, "placement": "55%", "avg_package": "3.2 LPA", "highest_package": "9 LPA",
        "seats": 2000, "criteria": "50% in 12th",
        "description": "State university in Sirsa offering arts, science and commerce programs.",
        "courses": ["arts"],
        "branches": ["BA", "BSc", "BCom", "MA", "MSc", "BCA"],
        "facilities": ["Library", "Hostel", "Sports Ground", "Labs"],
    },
    {
        "name": "Bhagat Phool Singh Mahila Vishwavidyalaya",
        "city": "Sonipat", "type": "Government", "category": "arts",
        "fees": 12000, "placement": "58%", "avg_package": "3 LPA", "highest_package": "8 LPA",
        "seats": 1800, "criteria": "50% in 12th (Women only)",
        "description": "Women's university in Khanpur Kalan, Sonipat offering arts, science and professional courses.",
        "courses": ["arts"],
        "branches": ["BA", "BSc", "BCom", "BCA", "MA", "MSc", "Nursing"],
        "facilities": ["Library", "Hostel", "Sports", "Labs", "Medical Centre"],
    },
    {
        "name": "Chaudhary Bansi Lal University",
        "city": "Bhiwani", "type": "Government", "category": "arts",
        "fees": 13000, "placement": "55%", "avg_package": "3 LPA", "highest_package": "8 LPA",
        "seats": 1500, "criteria": "50% in 12th",
        "description": "State university in Bhiwani offering arts, science and commerce.",
        "courses": ["arts"],
        "branches": ["BA", "BSc", "BCom", "MA", "MSc", "BCA"],
        "facilities": ["Library", "Hostel", "Sports Ground", "Labs"],
    },
    {
        "name": "Government College Ambala City",
        "city": "Ambala", "type": "Government", "category": "arts",
        "fees": 8000, "placement": "50%", "avg_package": "2.8 LPA", "highest_package": "7 LPA",
        "seats": 1200, "criteria": "50% in 12th",
        "description": "Government degree college in Ambala offering BA, BSc and BCom.",
        "courses": ["arts"],
        "branches": ["BA", "BSc", "BCom"],
        "facilities": ["Library", "Sports Ground", "Labs"],
    },
    {
        "name": "Government College Hisar",
        "city": "Hisar", "type": "Government", "category": "arts",
        "fees": 8000, "placement": "50%", "avg_package": "2.8 LPA", "highest_package": "7 LPA",
        "seats": 1400, "criteria": "50% in 12th",
        "description": "Government degree college in Hisar offering arts, science and commerce.",
        "courses": ["arts"],
        "branches": ["BA", "BSc", "BCom"],
        "facilities": ["Library", "Sports Ground", "Labs"],
    },
    {
        "name": "Government College Karnal",
        "city": "Karnal", "type": "Government", "category": "arts",
        "fees": 8000, "placement": "50%", "avg_package": "2.8 LPA", "highest_package": "7 LPA",
        "seats": 1300, "criteria": "50% in 12th",
        "description": "Government degree college in Karnal offering arts, science and commerce.",
        "courses": ["arts"],
        "branches": ["BA", "BSc", "BCom"],
        "facilities": ["Library", "Sports Ground", "Labs"],
    },
    {
        "name": "Government College Panipat",
        "city": "Panipat", "type": "Government", "category": "arts",
        "fees": 8000, "placement": "50%", "avg_package": "2.8 LPA", "highest_package": "7 LPA",
        "seats": 1200, "criteria": "50% in 12th",
        "description": "Government degree college in Panipat.",
        "courses": ["arts"],
        "branches": ["BA", "BSc", "BCom"],
        "facilities": ["Library", "Sports Ground", "Labs"],
    },
    {
        "name": "Vaish College Rohtak",
        "city": "Rohtak", "type": "Private", "category": "arts",
        "fees": 20000, "placement": "52%", "avg_package": "3 LPA", "highest_package": "8 LPA",
        "seats": 1000, "criteria": "50% in 12th",
        "description": "One of the oldest private colleges in Rohtak offering arts, science and commerce.",
        "courses": ["arts"],
        "branches": ["BA", "BSc", "BCom", "BCA"],
        "facilities": ["Library", "Sports Ground", "Labs", "Auditorium"],
    },
    {
        "name": "DAV College Ambala City",
        "city": "Ambala", "type": "Private", "category": "arts",
        "fees": 22000, "placement": "55%", "avg_package": "3.2 LPA", "highest_package": "9 LPA",
        "seats": 1100, "criteria": "50% in 12th",
        "description": "DAV affiliated college in Ambala offering arts, science and commerce.",
        "courses": ["arts"],
        "branches": ["BA", "BSc", "BCom", "BCA", "BBA"],
        "facilities": ["Library", "Sports Ground", "Labs", "Auditorium"],
    },
    {
        "name": "Arya PG College Panipat",
        "city": "Panipat", "type": "Private", "category": "arts",
        "fees": 18000, "placement": "50%", "avg_package": "2.8 LPA", "highest_package": "7 LPA",
        "seats": 800, "criteria": "50% in 12th",
        "description": "Private degree college in Panipat offering arts, science and commerce.",
        "courses": ["arts"],
        "branches": ["BA", "BSc", "BCom", "BCA"],
        "facilities": ["Library", "Sports Ground", "Labs"],
    },
    {
        "name": "SD College Ambala Cantt",
        "city": "Ambala", "type": "Private", "category": "arts",
        "fees": 19000, "placement": "52%", "avg_package": "3 LPA", "highest_package": "8 LPA",
        "seats": 900, "criteria": "50% in 12th",
        "description": "Sanatan Dharma College in Ambala Cantt offering arts, science and commerce.",
        "courses": ["arts"],
        "branches": ["BA", "BSc", "BCom", "BCA"],
        "facilities": ["Library", "Sports Ground", "Labs"],
    },
    {
        "name": "Government PG College Sirsa",
        "city": "Sirsa", "type": "Government", "category": "arts",
        "fees": 9000, "placement": "48%", "avg_package": "2.6 LPA", "highest_package": "6.5 LPA",
        "seats": 1100, "criteria": "50% in 12th",
        "description": "Government post-graduate college in Sirsa.",
        "courses": ["arts"],
        "branches": ["BA", "BSc", "BCom", "MA", "MSc"],
        "facilities": ["Library", "Sports Ground", "Labs"],
    },
    {
        "name": "Government PG College Rewari",
        "city": "Rewari", "type": "Government", "category": "arts",
        "fees": 9000, "placement": "48%", "avg_package": "2.6 LPA", "highest_package": "6.5 LPA",
        "seats": 1000, "criteria": "50% in 12th",
        "description": "Government post-graduate college in Rewari.",
        "courses": ["arts"],
        "branches": ["BA", "BSc", "BCom", "MA"],
        "facilities": ["Library", "Sports Ground", "Labs"],
    },

    # ── Polytechnic ──────────────────────────────────────────────────────────
    {
        "name": "Government Polytechnic Karnal",
        "city": "Karnal", "type": "Government", "category": "polytechnic",
        "fees": 25000, "placement": "70%", "avg_package": "3 LPA", "highest_package": "8 LPA",
        "seats": 600, "criteria": "50% in 10th",
        "description": "Government polytechnic college in Karnal offering diploma in engineering.",
        "courses": ["polytechnic"],
        "branches": ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Science"],
        "facilities": ["Library", "Hostel", "Workshop", "Labs"],
    },
    {
        "name": "Government Polytechnic Ambala",
        "city": "Ambala", "type": "Government", "category": "polytechnic",
        "fees": 24000, "placement": "68%", "avg_package": "2.8 LPA", "highest_package": "7 LPA",
        "seats": 480, "criteria": "50% in 10th",
        "description": "Government polytechnic in Ambala offering diploma engineering courses.",
        "courses": ["polytechnic"],
        "branches": ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Electronics"],
        "facilities": ["Library", "Hostel", "Workshop", "Labs"],
    },
    {
        "name": "Government Polytechnic Hisar",
        "city": "Hisar", "type": "Government", "category": "polytechnic",
        "fees": 24000, "placement": "67%", "avg_package": "2.8 LPA", "highest_package": "7 LPA",
        "seats": 480, "criteria": "50% in 10th",
        "description": "Government polytechnic in Hisar offering diploma engineering courses.",
        "courses": ["polytechnic"],
        "branches": ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Science"],
        "facilities": ["Library", "Hostel", "Workshop", "Labs"],
    },
    {
        "name": "Government Polytechnic Rohtak",
        "city": "Rohtak", "type": "Government", "category": "polytechnic",
        "fees": 24000, "placement": "68%", "avg_package": "2.9 LPA", "highest_package": "7.5 LPA",
        "seats": 480, "criteria": "50% in 10th",
        "description": "Government polytechnic in Rohtak offering diploma engineering courses.",
        "courses": ["polytechnic"],
        "branches": ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Science"],
        "facilities": ["Library", "Hostel", "Workshop", "Labs"],
    },
    {
        "name": "Government Polytechnic Faridabad",
        "city": "Faridabad", "type": "Government", "category": "polytechnic",
        "fees": 25000, "placement": "72%", "avg_package": "3.2 LPA", "highest_package": "8.5 LPA",
        "seats": 540, "criteria": "50% in 10th",
        "description": "Government polytechnic in Faridabad with strong industry placement.",
        "courses": ["polytechnic"],
        "branches": ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Science", "Electronics"],
        "facilities": ["Library", "Hostel", "Workshop", "Labs", "Sports Ground"],
    },
    {
        "name": "Government Polytechnic Gurgaon",
        "city": "Gurgaon", "type": "Government", "category": "polytechnic",
        "fees": 26000, "placement": "75%", "avg_package": "3.5 LPA", "highest_package": "9 LPA",
        "seats": 540, "criteria": "50% in 10th",
        "description": "Government polytechnic in Gurgaon with good placement due to proximity to industry.",
        "courses": ["polytechnic"],
        "branches": ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Science"],
        "facilities": ["Library", "Hostel", "Workshop", "Labs"],
    },
    {
        "name": "Government Polytechnic Panipat",
        "city": "Panipat", "type": "Government", "category": "polytechnic",
        "fees": 24000, "placement": "67%", "avg_package": "2.8 LPA", "highest_package": "7 LPA",
        "seats": 480, "criteria": "50% in 10th",
        "description": "Government polytechnic in Panipat offering diploma engineering courses.",
        "courses": ["polytechnic"],
        "branches": ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Science"],
        "facilities": ["Library", "Hostel", "Workshop", "Labs"],
    },
    {
        "name": "Government Polytechnic Sonipat",
        "city": "Sonipat", "type": "Government", "category": "polytechnic",
        "fees": 24000, "placement": "67%", "avg_package": "2.8 LPA", "highest_package": "7 LPA",
        "seats": 480, "criteria": "50% in 10th",
        "description": "Government polytechnic in Sonipat offering diploma engineering courses.",
        "courses": ["polytechnic"],
        "branches": ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Science"],
        "facilities": ["Library", "Hostel", "Workshop", "Labs"],
    },
    {
        "name": "Government Polytechnic Sirsa",
        "city": "Sirsa", "type": "Government", "category": "polytechnic",
        "fees": 23000, "placement": "65%", "avg_package": "2.7 LPA", "highest_package": "6.5 LPA",
        "seats": 360, "criteria": "50% in 10th",
        "description": "Government polytechnic in Sirsa offering diploma engineering courses.",
        "courses": ["polytechnic"],
        "branches": ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering"],
        "facilities": ["Library", "Hostel", "Workshop", "Labs"],
    },
    {
        "name": "Haryana Institute of Technology Sonipat",
        "city": "Sonipat", "type": "Private", "category": "polytechnic",
        "fees": 35000, "placement": "65%", "avg_package": "2.8 LPA", "highest_package": "7 LPA",
        "seats": 360, "criteria": "45% in 10th",
        "description": "Private polytechnic institute in Sonipat.",
        "courses": ["polytechnic"],
        "branches": ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Science"],
        "facilities": ["Library", "Workshop", "Labs"],
    },
    {
        "name": "Haryana Polytechnic Nilokheri",
        "city": "Karnal", "type": "Government", "category": "polytechnic",
        "fees": 23000, "placement": "66%", "avg_package": "2.8 LPA", "highest_package": "7 LPA",
        "seats": 360, "criteria": "50% in 10th",
        "description": "Government polytechnic in Nilokheri, Karnal district.",
        "courses": ["polytechnic"],
        "branches": ["Mechanical Engineering", "Electrical Engineering", "Computer Science"],
        "facilities": ["Library", "Workshop", "Labs"],
    },
]
